name: Cloudnative-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secret-scanning:
    uses: ./.github/workflows/secret-scan.yml

  lint:
    needs: [secret-scanning]
    uses: ./.github/workflows/lint.yml

  code-test:
    needs: [lint]
    uses: ./.github/workflows/code-test.yml

  SCA:
    needs: [lint,secret-scanning,code-test]
    uses: ./.github/workflows/SCA.yml
