name: Cloudnative-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:

  secret-scanning:
    name: Secret Scanning
    uses: ./.github/workflows/secret-scan.yml

  lint:
    name: Code Linting
    needs: [secret-scanning]
    uses: ./.github/workflows/lint.yml

  code-test:
    name: Unit & Integration Tests
    needs: [lint]
    uses: ./.github/workflows/code-test.yml

  sca-scan:
    name: Software Composition Analysis (SCA)
    needs: [lint]
    uses: ./.github/workflows/SCA.yml

  code-ql:
    name: CodeQL Security Scan
    needs: [code-test]
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ./.github/workflows/code-ql.yml

  sonar-scan:
    name: SonarQube Code Analysis
    needs: [code-test]
    uses: ./.github/workflows/sonarcube.yml
    secrets: inherit

  hadolint:
    name: Hadolint Dockerfile Linting
    needs: [code-test]
    uses: ./.github/workflows/docker-hadolint.yml

  docker-scan:
    name: Docker Security Scan (Trivy)
    needs: [hadolint]
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit

  docker-push:
    name: Push Docker Images
    needs: [docker-scan]
    uses: ./.github/workflows/docker-push.yml
    secrets: inherit

  deploy:
    name: Continuous Deployment
    needs: [docker-push]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  owasp-zap:
    name: OWASP ZAP DAST Scan
    needs: [deploy]
    uses: ./.github/workflows/zap-scan.yml
    with:
      target_url: ${{ secrets.APP_URL }}
    secrets: inherit
