name: SCA-check

on:
  workflow_call:

jobs:

  sca-javascript:
    name: SCA - ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: frontend
            name: frontend
          - folder: gateway
            name: gateway
          - folder: services/payment-service
            name: payment-service

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: ${{ matrix.folder }}/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Generate Dependency Report
        run: |
          npm audit --json > npm-audit-report.json || true

      - name: Upload Dependency Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-security-report-${{ matrix.name }}
          path: ${{ matrix.folder }}/npm-audit-report.json
          retention-days: 5

  sca-go:
    name: SCA - Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
          cache-dependency-path: services/auth-service/go.sum

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Go SCA
        working-directory: services/auth-service
        run: govulncheck ./...

  sca-python:
    name: SCA - Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: services/product-service/requirements.txt

      - name: Install Dependencies
        working-directory: services/product-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run Python SCA
        working-directory: services/product-service
        run: pip-audit -r requirements.txt